### ISSUE TITLE
no visit data in the package release in the neuroconductor

### ISSUE THREAD

**Issue by ulysses1881826** [muschellij2/kirby21.t1#1]
Sorry to trouble you here
I start to try your packages today, but I find one problem. When using "neuro_install('kirby21.t1')" to install "kirby21.t1", we usually download the release from the "https://neuroconductor.org/releases/2019/07/src/contrib/kirby21.t1_1.7.0.tar.gz". However, this zip file maybe forget to package the "visit_1" and "visit_2" data into. The result is when you use  function like "fnames = get_image_filenames_df(ids = 113, modalities = c("T1"), visits = c(1),long = FALSE)", you will get NULL finally, since no visit data included in the package. The same is for "t2", but "kirby21.mricloud" seems to be right including the "visit" data.
Hope you can look into it and check it.
Thanks~

**Comment by muschellij2** [comment]
Run `kirby21.t1::download_t1_data` to download the data.
